version: '3.4'

services:
  elasticsearch.webapi:
    image: ${DOCKER_REGISTRY-}elasticsearchapi
    build:
      context: .
      dockerfile: ElasticSearch.WebApi/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2

networks:
  elastic:
    driver: bridge
    
volumes:
  elasticsearch-data: 